//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 06:47:13 PM GMT 
//
@XmlSchema(xmlns = {
        @XmlNs(
                prefix = "SOAP-ENV",
                namespaceURI="http://www.w3.org/2001/12/soap-envelope"
        )}
        , elementFormDefault = XmlNsForm.QUALIFIED
        , namespace="http://www.w3.org/2001/12/soap-envelope"
)
package com.vodafone.charging.accountservice.domain.xml;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;


