//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 06:47:13 PM GMT 
//


package com.vodafone.charging.accountservice.domain.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}accountId"/&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}clientId"/&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}kycCheck"/&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}serviceId"/&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}partnerId"/&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}packageType"/&gt;
 *         &lt;element ref="{http://www.vizzavi.net/chargingandpayments/message/1.0}vendorId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "accountId",
        "serviceId",
        "partnerId",
        "packageType",
        "vendorId",
        "clientId",
        "kycCheck"
})
@XmlRootElement(name = "validate")
public class Validate {

    @XmlElement(required = true, namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected AccountId accountId;
    @XmlElement(namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected String clientId;
    @XmlElement(namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected boolean kycCheck;
    @XmlElement(namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected String serviceId;
    @XmlElement(namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected String partnerId;
    @XmlElement(namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected String packageType;
    @XmlElement(namespace="http://www.vizzavi.net/chargingandpayments/message/1.0")
    protected String vendorId;

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link AccountId }
     *     
     */
    public AccountId getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountId }
     *     
     */
    public void setAccountId(AccountId value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the kycCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public boolean isKycCheck() {
        return kycCheck;
    }

    /**
     * Sets the value of the kycCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKycCheck(boolean value) {
        this.kycCheck = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the partnerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * Sets the value of the partnerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerId(String value) {
        this.partnerId = value;
    }

    /**
     * Gets the value of the packageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageType() {
        return packageType;
    }

    /**
     * Sets the value of the packageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageType(String value) {
        this.packageType = value;
    }

    /**
     * Gets the value of the vendorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorId() {
        return vendorId;
    }

    /**
     * Sets the value of the vendorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorId(String value) {
        this.vendorId = value;
    }

}
